package me.mark.partikt

fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> id(fn: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T = fn

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).not() = rev(this)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> rev(crossinline fn: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T): (S, R, Q, P, O, N, M, L, K, J, I, H, G, F, E, D, C, B, A) -> T = { s, r, q, p, o, n, m, l, k, j, i, h, g, f, e, d, c, b, a -> fn(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s)}

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).plus(a: A): (B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T = par(a)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).par(a: A): (B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T = { b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).par(a: A, b: B): (C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T = { c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).par(a: A, b: B, c: C): (D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T = { d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).par(a: A, b: B, c: C, d: D): (E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T = { e, f, g, h, i, j, k, l, m, n, o, p, q, r, s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).par(a: A, b: B, c: C, d: D, e: E): (F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T = { f, g, h, i, j, k, l, m, n, o, p, q, r, s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).par(a: A, b: B, c: C, d: D, e: E, f: F): (G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T = { g, h, i, j, k, l, m, n, o, p, q, r, s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G): (H, I, J, K, L, M, N, O, P, Q, R, S) -> T = { h, i, j, k, l, m, n, o, p, q, r, s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H): (I, J, K, L, M, N, O, P, Q, R, S) -> T = { i, j, k, l, m, n, o, p, q, r, s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I): (J, K, L, M, N, O, P, Q, R, S) -> T = { j, k, l, m, n, o, p, q, r, s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J): (K, L, M, N, O, P, Q, R, S) -> T = { k, l, m, n, o, p, q, r, s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K): (L, M, N, O, P, Q, R, S) -> T = { l, m, n, o, p, q, r, s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L): (M, N, O, P, Q, R, S) -> T = { m, n, o, p, q, r, s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M): (N, O, P, Q, R, S) -> T = { n, o, p, q, r, s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N): (O, P, Q, R, S) -> T = { o, p, q, r, s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O): (P, Q, R, S) -> T = { p, q, r, s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P): (Q, R, S) -> T = { q, r, s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q): (R, S) -> T = { r, s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R): (S) -> T = { s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).minus(s: S): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> T = rep(s)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).rep(s: S): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> T = { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).rep(r: R, s: S): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> T = { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).rep(q: Q, r: R, s: S): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> T = { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).rep(p: P, q: Q, r: R, s: S): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> T = { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).rep(o: O, p: P, q: Q, r: R, s: S): (A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> T = { a, b, c, d, e, f, g, h, i, j, k, l, m, n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).rep(n: N, o: O, p: P, q: Q, r: R, s: S): (A, B, C, D, E, F, G, H, I, J, K, L, M) -> T = { a, b, c, d, e, f, g, h, i, j, k, l, m -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).rep(m: M, n: N, o: O, p: P, q: Q, r: R, s: S): (A, B, C, D, E, F, G, H, I, J, K, L) -> T = { a, b, c, d, e, f, g, h, i, j, k, l -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).rep(l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S): (A, B, C, D, E, F, G, H, I, J, K) -> T = { a, b, c, d, e, f, g, h, i, j, k -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).rep(k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S): (A, B, C, D, E, F, G, H, I, J) -> T = { a, b, c, d, e, f, g, h, i, j -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).rep(j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S): (A, B, C, D, E, F, G, H, I) -> T = { a, b, c, d, e, f, g, h, i -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).rep(i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S): (A, B, C, D, E, F, G, H) -> T = { a, b, c, d, e, f, g, h -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).rep(h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S): (A, B, C, D, E, F, G) -> T = { a, b, c, d, e, f, g -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).rep(g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S): (A, B, C, D, E, F) -> T = { a, b, c, d, e, f -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).rep(f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S): (A, B, C, D, E) -> T = { a, b, c, d, e -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).rep(e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S): (A, B, C, D) -> T = { a, b, c, d -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).rep(d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S): (A, B, C) -> T = { a, b, c -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).rep(c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S): (A, B) -> T = { a, b -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> T).rep(b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S): (A) -> T = { a -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) }
