package me.mark.partikt

fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> id(fn: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R = fn

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).not() = rev(this)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> rev(crossinline fn: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R): (Q, P, O, N, M, L, K, J, I, H, G, F, E, D, C, B, A) -> R = { q, p, o, n, m, l, k, j, i, h, g, f, e, d, c, b, a -> fn(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q)}

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).plus(a: A): (B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R = par(a)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).par(a: A): (B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R = { b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).par(a: A, b: B): (C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R = { c, d, e, f, g, h, i, j, k, l, m, n, o, p, q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).par(a: A, b: B, c: C): (D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R = { d, e, f, g, h, i, j, k, l, m, n, o, p, q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).par(a: A, b: B, c: C, d: D): (E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R = { e, f, g, h, i, j, k, l, m, n, o, p, q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).par(a: A, b: B, c: C, d: D, e: E): (F, G, H, I, J, K, L, M, N, O, P, Q) -> R = { f, g, h, i, j, k, l, m, n, o, p, q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).par(a: A, b: B, c: C, d: D, e: E, f: F): (G, H, I, J, K, L, M, N, O, P, Q) -> R = { g, h, i, j, k, l, m, n, o, p, q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G): (H, I, J, K, L, M, N, O, P, Q) -> R = { h, i, j, k, l, m, n, o, p, q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H): (I, J, K, L, M, N, O, P, Q) -> R = { i, j, k, l, m, n, o, p, q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I): (J, K, L, M, N, O, P, Q) -> R = { j, k, l, m, n, o, p, q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J): (K, L, M, N, O, P, Q) -> R = { k, l, m, n, o, p, q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K): (L, M, N, O, P, Q) -> R = { l, m, n, o, p, q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L): (M, N, O, P, Q) -> R = { m, n, o, p, q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M): (N, O, P, Q) -> R = { n, o, p, q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N): (O, P, Q) -> R = { o, p, q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O): (P, Q) -> R = { p, q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P): (Q) -> R = { q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).minus(q: Q): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> R = rep(q)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).rep(q: Q): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> R = { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).rep(p: P, q: Q): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> R = { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).rep(o: O, p: P, q: Q): (A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> R = { a, b, c, d, e, f, g, h, i, j, k, l, m, n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).rep(n: N, o: O, p: P, q: Q): (A, B, C, D, E, F, G, H, I, J, K, L, M) -> R = { a, b, c, d, e, f, g, h, i, j, k, l, m -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).rep(m: M, n: N, o: O, p: P, q: Q): (A, B, C, D, E, F, G, H, I, J, K, L) -> R = { a, b, c, d, e, f, g, h, i, j, k, l -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).rep(l: L, m: M, n: N, o: O, p: P, q: Q): (A, B, C, D, E, F, G, H, I, J, K) -> R = { a, b, c, d, e, f, g, h, i, j, k -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).rep(k: K, l: L, m: M, n: N, o: O, p: P, q: Q): (A, B, C, D, E, F, G, H, I, J) -> R = { a, b, c, d, e, f, g, h, i, j -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).rep(j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q): (A, B, C, D, E, F, G, H, I) -> R = { a, b, c, d, e, f, g, h, i -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).rep(i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q): (A, B, C, D, E, F, G, H) -> R = { a, b, c, d, e, f, g, h -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).rep(h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q): (A, B, C, D, E, F, G) -> R = { a, b, c, d, e, f, g -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).rep(g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q): (A, B, C, D, E, F) -> R = { a, b, c, d, e, f -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).rep(f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q): (A, B, C, D, E) -> R = { a, b, c, d, e -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).rep(e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q): (A, B, C, D) -> R = { a, b, c, d -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).rep(d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q): (A, B, C) -> R = { a, b, c -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).rep(c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q): (A, B) -> R = { a, b -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> R).rep(b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q): (A) -> R = { a -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) }
