package me.mark.partikt

fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> id(fn: (A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O): (A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O = fn

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).not() = rev(this)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> rev(crossinline fn: (A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O): (N, M, L, K, J, I, H, G, F, E, D, C, B, A) -> O = { n, m, l, k, j, i, h, g, f, e, d, c, b, a -> fn(a, b, c, d, e, f, g, h, i, j, k, l, m, n)}

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).plus(a: A): (B, C, D, E, F, G, H, I, J, K, L, M, N) -> O = par(a)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).par(a: A): (B, C, D, E, F, G, H, I, J, K, L, M, N) -> O = { b, c, d, e, f, g, h, i, j, k, l, m, n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).par(a: A, b: B): (C, D, E, F, G, H, I, J, K, L, M, N) -> O = { c, d, e, f, g, h, i, j, k, l, m, n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).par(a: A, b: B, c: C): (D, E, F, G, H, I, J, K, L, M, N) -> O = { d, e, f, g, h, i, j, k, l, m, n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).par(a: A, b: B, c: C, d: D): (E, F, G, H, I, J, K, L, M, N) -> O = { e, f, g, h, i, j, k, l, m, n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).par(a: A, b: B, c: C, d: D, e: E): (F, G, H, I, J, K, L, M, N) -> O = { f, g, h, i, j, k, l, m, n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).par(a: A, b: B, c: C, d: D, e: E, f: F): (G, H, I, J, K, L, M, N) -> O = { g, h, i, j, k, l, m, n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G): (H, I, J, K, L, M, N) -> O = { h, i, j, k, l, m, n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H): (I, J, K, L, M, N) -> O = { i, j, k, l, m, n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I): (J, K, L, M, N) -> O = { j, k, l, m, n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J): (K, L, M, N) -> O = { k, l, m, n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K): (L, M, N) -> O = { l, m, n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L): (M, N) -> O = { m, n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M): (N) -> O = { n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).minus(n: N): (A, B, C, D, E, F, G, H, I, J, K, L, M) -> O = rep(n)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).rep(n: N): (A, B, C, D, E, F, G, H, I, J, K, L, M) -> O = { a, b, c, d, e, f, g, h, i, j, k, l, m -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).rep(m: M, n: N): (A, B, C, D, E, F, G, H, I, J, K, L) -> O = { a, b, c, d, e, f, g, h, i, j, k, l -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).rep(l: L, m: M, n: N): (A, B, C, D, E, F, G, H, I, J, K) -> O = { a, b, c, d, e, f, g, h, i, j, k -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).rep(k: K, l: L, m: M, n: N): (A, B, C, D, E, F, G, H, I, J) -> O = { a, b, c, d, e, f, g, h, i, j -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).rep(j: J, k: K, l: L, m: M, n: N): (A, B, C, D, E, F, G, H, I) -> O = { a, b, c, d, e, f, g, h, i -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).rep(i: I, j: J, k: K, l: L, m: M, n: N): (A, B, C, D, E, F, G, H) -> O = { a, b, c, d, e, f, g, h -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).rep(h: H, i: I, j: J, k: K, l: L, m: M, n: N): (A, B, C, D, E, F, G) -> O = { a, b, c, d, e, f, g -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).rep(g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N): (A, B, C, D, E, F) -> O = { a, b, c, d, e, f -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).rep(f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N): (A, B, C, D, E) -> O = { a, b, c, d, e -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).rep(e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N): (A, B, C, D) -> O = { a, b, c, d -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).rep(d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N): (A, B, C) -> O = { a, b, c -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).rep(c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N): (A, B) -> O = { a, b -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> O).rep(b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N): (A) -> O = { a -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n) }
