package me.mark.partikt

fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> id(fn: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S = fn

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).not() = rev(this)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> rev(crossinline fn: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S): (R, Q, P, O, N, M, L, K, J, I, H, G, F, E, D, C, B, A) -> S = { r, q, p, o, n, m, l, k, j, i, h, g, f, e, d, c, b, a -> fn(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r)}

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).plus(a: A): (B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S = par(a)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).par(a: A): (B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S = { b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).par(a: A, b: B): (C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S = { c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).par(a: A, b: B, c: C): (D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S = { d, e, f, g, h, i, j, k, l, m, n, o, p, q, r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).par(a: A, b: B, c: C, d: D): (E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S = { e, f, g, h, i, j, k, l, m, n, o, p, q, r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).par(a: A, b: B, c: C, d: D, e: E): (F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S = { f, g, h, i, j, k, l, m, n, o, p, q, r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).par(a: A, b: B, c: C, d: D, e: E, f: F): (G, H, I, J, K, L, M, N, O, P, Q, R) -> S = { g, h, i, j, k, l, m, n, o, p, q, r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G): (H, I, J, K, L, M, N, O, P, Q, R) -> S = { h, i, j, k, l, m, n, o, p, q, r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H): (I, J, K, L, M, N, O, P, Q, R) -> S = { i, j, k, l, m, n, o, p, q, r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I): (J, K, L, M, N, O, P, Q, R) -> S = { j, k, l, m, n, o, p, q, r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J): (K, L, M, N, O, P, Q, R) -> S = { k, l, m, n, o, p, q, r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K): (L, M, N, O, P, Q, R) -> S = { l, m, n, o, p, q, r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L): (M, N, O, P, Q, R) -> S = { m, n, o, p, q, r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M): (N, O, P, Q, R) -> S = { n, o, p, q, r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N): (O, P, Q, R) -> S = { o, p, q, r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O): (P, Q, R) -> S = { p, q, r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P): (Q, R) -> S = { q, r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q): (R) -> S = { r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).minus(r: R): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> S = rep(r)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).rep(r: R): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> S = { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).rep(q: Q, r: R): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> S = { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).rep(p: P, q: Q, r: R): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> S = { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).rep(o: O, p: P, q: Q, r: R): (A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> S = { a, b, c, d, e, f, g, h, i, j, k, l, m, n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).rep(n: N, o: O, p: P, q: Q, r: R): (A, B, C, D, E, F, G, H, I, J, K, L, M) -> S = { a, b, c, d, e, f, g, h, i, j, k, l, m -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).rep(m: M, n: N, o: O, p: P, q: Q, r: R): (A, B, C, D, E, F, G, H, I, J, K, L) -> S = { a, b, c, d, e, f, g, h, i, j, k, l -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).rep(l: L, m: M, n: N, o: O, p: P, q: Q, r: R): (A, B, C, D, E, F, G, H, I, J, K) -> S = { a, b, c, d, e, f, g, h, i, j, k -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).rep(k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R): (A, B, C, D, E, F, G, H, I, J) -> S = { a, b, c, d, e, f, g, h, i, j -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).rep(j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R): (A, B, C, D, E, F, G, H, I) -> S = { a, b, c, d, e, f, g, h, i -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).rep(i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R): (A, B, C, D, E, F, G, H) -> S = { a, b, c, d, e, f, g, h -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).rep(h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R): (A, B, C, D, E, F, G) -> S = { a, b, c, d, e, f, g -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).rep(g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R): (A, B, C, D, E, F) -> S = { a, b, c, d, e, f -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).rep(f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R): (A, B, C, D, E) -> S = { a, b, c, d, e -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).rep(e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R): (A, B, C, D) -> S = { a, b, c, d -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).rep(d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R): (A, B, C) -> S = { a, b, c -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).rep(c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R): (A, B) -> S = { a, b -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> S).rep(b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R): (A) -> S = { a -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) }
