package me.mark.partikt

fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> id(fn: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U = fn

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).not() = rev(this)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> rev(crossinline fn: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U): (T, S, R, Q, P, O, N, M, L, K, J, I, H, G, F, E, D, C, B, A) -> U = { t, s, r, q, p, o, n, m, l, k, j, i, h, g, f, e, d, c, b, a -> fn(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t)}

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).plus(a: A): (B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U = par(a)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A): (B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U = { b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A, b: B): (C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U = { c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A, b: B, c: C): (D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U = { d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A, b: B, c: C, d: D): (E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U = { e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A, b: B, c: C, d: D, e: E): (F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U = { f, g, h, i, j, k, l, m, n, o, p, q, r, s, t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A, b: B, c: C, d: D, e: E, f: F): (G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U = { g, h, i, j, k, l, m, n, o, p, q, r, s, t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G): (H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U = { h, i, j, k, l, m, n, o, p, q, r, s, t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H): (I, J, K, L, M, N, O, P, Q, R, S, T) -> U = { i, j, k, l, m, n, o, p, q, r, s, t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I): (J, K, L, M, N, O, P, Q, R, S, T) -> U = { j, k, l, m, n, o, p, q, r, s, t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J): (K, L, M, N, O, P, Q, R, S, T) -> U = { k, l, m, n, o, p, q, r, s, t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K): (L, M, N, O, P, Q, R, S, T) -> U = { l, m, n, o, p, q, r, s, t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L): (M, N, O, P, Q, R, S, T) -> U = { m, n, o, p, q, r, s, t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M): (N, O, P, Q, R, S, T) -> U = { n, o, p, q, r, s, t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N): (O, P, Q, R, S, T) -> U = { o, p, q, r, s, t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O): (P, Q, R, S, T) -> U = { p, q, r, s, t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P): (Q, R, S, T) -> U = { q, r, s, t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q): (R, S, T) -> U = { r, s, t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R): (S, T) -> U = { s, t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S): (T) -> U = { t -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).minus(t: T): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> U = rep(t)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(t: T): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) -> U = { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(s: S, t: T): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) -> U = { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(r: R, s: S, t: T): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) -> U = { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(q: Q, r: R, s: S, t: T): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> U = { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(p: P, q: Q, r: R, s: S, t: T): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> U = { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(o: O, p: P, q: Q, r: R, s: S, t: T): (A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> U = { a, b, c, d, e, f, g, h, i, j, k, l, m, n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(n: N, o: O, p: P, q: Q, r: R, s: S, t: T): (A, B, C, D, E, F, G, H, I, J, K, L, M) -> U = { a, b, c, d, e, f, g, h, i, j, k, l, m -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(m: M, n: N, o: O, p: P, q: Q, r: R, s: S, t: T): (A, B, C, D, E, F, G, H, I, J, K, L) -> U = { a, b, c, d, e, f, g, h, i, j, k, l -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S, t: T): (A, B, C, D, E, F, G, H, I, J, K) -> U = { a, b, c, d, e, f, g, h, i, j, k -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S, t: T): (A, B, C, D, E, F, G, H, I, J) -> U = { a, b, c, d, e, f, g, h, i, j -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S, t: T): (A, B, C, D, E, F, G, H, I) -> U = { a, b, c, d, e, f, g, h, i -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S, t: T): (A, B, C, D, E, F, G, H) -> U = { a, b, c, d, e, f, g, h -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S, t: T): (A, B, C, D, E, F, G) -> U = { a, b, c, d, e, f, g -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S, t: T): (A, B, C, D, E, F) -> U = { a, b, c, d, e, f -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S, t: T): (A, B, C, D, E) -> U = { a, b, c, d, e -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S, t: T): (A, B, C, D) -> U = { a, b, c, d -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S, t: T): (A, B, C) -> U = { a, b, c -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S, t: T): (A, B) -> U = { a, b -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) -> U).rep(b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P, q: Q, r: R, s: S, t: T): (A) -> U = { a -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) }
