package me.mark.partikt

fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> id(fn: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P = fn

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).not() = rev(this)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> rev(crossinline fn: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P): (O, N, M, L, K, J, I, H, G, F, E, D, C, B, A) -> P = { o, n, m, l, k, j, i, h, g, f, e, d, c, b, a -> fn(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o)}

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).plus(a: A): (B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P = par(a)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).par(a: A): (B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P = { b, c, d, e, f, g, h, i, j, k, l, m, n, o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).par(a: A, b: B): (C, D, E, F, G, H, I, J, K, L, M, N, O) -> P = { c, d, e, f, g, h, i, j, k, l, m, n, o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).par(a: A, b: B, c: C): (D, E, F, G, H, I, J, K, L, M, N, O) -> P = { d, e, f, g, h, i, j, k, l, m, n, o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).par(a: A, b: B, c: C, d: D): (E, F, G, H, I, J, K, L, M, N, O) -> P = { e, f, g, h, i, j, k, l, m, n, o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).par(a: A, b: B, c: C, d: D, e: E): (F, G, H, I, J, K, L, M, N, O) -> P = { f, g, h, i, j, k, l, m, n, o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).par(a: A, b: B, c: C, d: D, e: E, f: F): (G, H, I, J, K, L, M, N, O) -> P = { g, h, i, j, k, l, m, n, o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G): (H, I, J, K, L, M, N, O) -> P = { h, i, j, k, l, m, n, o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H): (I, J, K, L, M, N, O) -> P = { i, j, k, l, m, n, o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I): (J, K, L, M, N, O) -> P = { j, k, l, m, n, o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J): (K, L, M, N, O) -> P = { k, l, m, n, o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K): (L, M, N, O) -> P = { l, m, n, o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L): (M, N, O) -> P = { m, n, o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M): (N, O) -> P = { n, o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N): (O) -> P = { o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).minus(o: O): (A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> P = rep(o)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).rep(o: O): (A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> P = { a, b, c, d, e, f, g, h, i, j, k, l, m, n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).rep(n: N, o: O): (A, B, C, D, E, F, G, H, I, J, K, L, M) -> P = { a, b, c, d, e, f, g, h, i, j, k, l, m -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).rep(m: M, n: N, o: O): (A, B, C, D, E, F, G, H, I, J, K, L) -> P = { a, b, c, d, e, f, g, h, i, j, k, l -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).rep(l: L, m: M, n: N, o: O): (A, B, C, D, E, F, G, H, I, J, K) -> P = { a, b, c, d, e, f, g, h, i, j, k -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).rep(k: K, l: L, m: M, n: N, o: O): (A, B, C, D, E, F, G, H, I, J) -> P = { a, b, c, d, e, f, g, h, i, j -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).rep(j: J, k: K, l: L, m: M, n: N, o: O): (A, B, C, D, E, F, G, H, I) -> P = { a, b, c, d, e, f, g, h, i -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).rep(i: I, j: J, k: K, l: L, m: M, n: N, o: O): (A, B, C, D, E, F, G, H) -> P = { a, b, c, d, e, f, g, h -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).rep(h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O): (A, B, C, D, E, F, G) -> P = { a, b, c, d, e, f, g -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).rep(g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O): (A, B, C, D, E, F) -> P = { a, b, c, d, e, f -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).rep(f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O): (A, B, C, D, E) -> P = { a, b, c, d, e -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).rep(e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O): (A, B, C, D) -> P = { a, b, c, d -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).rep(d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O): (A, B, C) -> P = { a, b, c -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).rep(c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O): (A, B) -> P = { a, b -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> P).rep(b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O): (A) -> P = { a -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) }
