package me.mark.partikt

fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> id(fn: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q = fn

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).not() = rev(this)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> rev(crossinline fn: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q): (P, O, N, M, L, K, J, I, H, G, F, E, D, C, B, A) -> Q = { p, o, n, m, l, k, j, i, h, g, f, e, d, c, b, a -> fn(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p)}

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).plus(a: A): (B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q = par(a)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).par(a: A): (B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q = { b, c, d, e, f, g, h, i, j, k, l, m, n, o, p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).par(a: A, b: B): (C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q = { c, d, e, f, g, h, i, j, k, l, m, n, o, p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).par(a: A, b: B, c: C): (D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q = { d, e, f, g, h, i, j, k, l, m, n, o, p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).par(a: A, b: B, c: C, d: D): (E, F, G, H, I, J, K, L, M, N, O, P) -> Q = { e, f, g, h, i, j, k, l, m, n, o, p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).par(a: A, b: B, c: C, d: D, e: E): (F, G, H, I, J, K, L, M, N, O, P) -> Q = { f, g, h, i, j, k, l, m, n, o, p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).par(a: A, b: B, c: C, d: D, e: E, f: F): (G, H, I, J, K, L, M, N, O, P) -> Q = { g, h, i, j, k, l, m, n, o, p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G): (H, I, J, K, L, M, N, O, P) -> Q = { h, i, j, k, l, m, n, o, p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H): (I, J, K, L, M, N, O, P) -> Q = { i, j, k, l, m, n, o, p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I): (J, K, L, M, N, O, P) -> Q = { j, k, l, m, n, o, p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J): (K, L, M, N, O, P) -> Q = { k, l, m, n, o, p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K): (L, M, N, O, P) -> Q = { l, m, n, o, p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L): (M, N, O, P) -> Q = { m, n, o, p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M): (N, O, P) -> Q = { n, o, p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N): (O, P) -> Q = { o, p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).par(a: A, b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O): (P) -> Q = { p -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }

inline operator fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).minus(p: P): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> Q = rep(p)
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).rep(p: P): (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) -> Q = { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).rep(o: O, p: P): (A, B, C, D, E, F, G, H, I, J, K, L, M, N) -> Q = { a, b, c, d, e, f, g, h, i, j, k, l, m, n -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).rep(n: N, o: O, p: P): (A, B, C, D, E, F, G, H, I, J, K, L, M) -> Q = { a, b, c, d, e, f, g, h, i, j, k, l, m -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).rep(m: M, n: N, o: O, p: P): (A, B, C, D, E, F, G, H, I, J, K, L) -> Q = { a, b, c, d, e, f, g, h, i, j, k, l -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).rep(l: L, m: M, n: N, o: O, p: P): (A, B, C, D, E, F, G, H, I, J, K) -> Q = { a, b, c, d, e, f, g, h, i, j, k -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).rep(k: K, l: L, m: M, n: N, o: O, p: P): (A, B, C, D, E, F, G, H, I, J) -> Q = { a, b, c, d, e, f, g, h, i, j -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).rep(j: J, k: K, l: L, m: M, n: N, o: O, p: P): (A, B, C, D, E, F, G, H, I) -> Q = { a, b, c, d, e, f, g, h, i -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).rep(i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P): (A, B, C, D, E, F, G, H) -> Q = { a, b, c, d, e, f, g, h -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).rep(h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P): (A, B, C, D, E, F, G) -> Q = { a, b, c, d, e, f, g -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).rep(g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P): (A, B, C, D, E, F) -> Q = { a, b, c, d, e, f -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).rep(f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P): (A, B, C, D, E) -> Q = { a, b, c, d, e -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).rep(e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P): (A, B, C, D) -> Q = { a, b, c, d -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).rep(d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P): (A, B, C) -> Q = { a, b, c -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).rep(c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P): (A, B) -> Q = { a, b -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
inline fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> ((A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) -> Q).rep(b: B, c: C, d: D, e: E, f: F, g: G, h: H, i: I, j: J, k: K, l: L, m: M, n: N, o: O, p: P): (A) -> Q = { a -> this(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) }
